server.port=9100

management.endpoints.web.exposure.include=gateway,health

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:9102/eureka/
eureka.instance.prefer-ip-address=true

# Routes
spring.cloud.gateway.mvc.routes[0].id=account-service
spring.cloud.gateway.mvc.routes[0].uri=lb://account-microservice
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/accounts,/accounts/**

spring.cloud.gateway.mvc.routes[1].id=card-service
spring.cloud.gateway.mvc.routes[1].uri=lb://card-microservice
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/cards,/cards/**

spring.cloud.gateway.mvc.routes[2].id=transaction-service
spring.cloud.gateway.mvc.routes[2].uri=lb://transaction-microservice
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/transactions,/transactions/**

spring.cloud.gateway.mvc.routes[3].id=virement
spring.cloud.gateway.mvc.routes[3].uri=lb://transaction-microservice
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/virement

spring.cloud.gateway.mvc.routes[4].id=retrait
spring.cloud.gateway.mvc.routes[4].uri=lb://transaction-microservice
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/retrait
