server.port=9002

spring.datasource.url=jdbc:postgresql://localhost:5434/db-transaction
spring.datasource.username=admin
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

#Cree/maj les table a partire de Entity
spring.jpa.hibernate.ddl-auto=create-drop
management.endpoints.web.exposure.include=refresh, health

#Eureka
eureka.client.serviceUrl.defaultZone: http://localhost:9102/eureka/
eureka.instance.prefer-ip-address=true
